# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_designer_files/abstract.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_abstract = QtWidgets.QLabel(self.centralwidget)
        self.lbl_abstract.setGeometry(QtCore.QRect(10, 20, 67, 22))
        self.lbl_abstract.setObjectName("lbl_abstract")
        self.txt_abstract = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_abstract.setGeometry(QtCore.QRect(10, 50, 491, 471))
        self.txt_abstract.setObjectName("txt_abstract")
        self.btn_process = QtWidgets.QPushButton(self.centralwidget)
        self.btn_process.setGeometry(QtCore.QRect(510, 50, 101, 38))
        self.btn_process.setObjectName("btn_process")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Abstract GUI"))
        self.lbl_abstract.setText(_translate("MainWindow", "Abstract"))
        self.btn_process.setText(_translate("MainWindow", "process"))
